server:
  port: 8005
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    # 在dev环境开启mybatis的日志打印
  data:
    mogodb:
      uri: mongodb://root@121.196.154.56:27017
      database: soft_news
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    设置域名，这里是资源配置
website:
  domain-name: admin.sn.com